### ISSUE TITLE
LLVM AddressSanitizer detects memory leak  in tree_sitter_matlab_external_scanner_create

### ISSUE THREAD

**Issue by nordlow** [acristoffers/tree-sitter-matlab#6]
LLVM AddressSanitizer detects memory leak  in call to `calloc` in `tree_sitter_matlab_external_scanner_create`

```
Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x55cbedbb4078 in calloc /home/runner/work/llvm-project/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:77:3
    #1 0x7f8bf2407503 in tree_sitter_matlab_external_scanner_create (libtree-sitter-matlab.so+0x207503)
    #2 0x7f8c2cc7d72e in ts_parser_set_language (/lib/x86_64-linux-gnu/libtree-sitter.so.0+0xd72e) (BuildId: 5ef1a1d89567ecf8c93d7456cd5701276d398db0)

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
Error Program exited with code 1
```

See https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer.

**Comment by acristoffers** [comment]
Thanks for the report :)
